import "./globals.css";
import ResponsiveAppBar from "@components/Navbar/ResponsiveAppBar";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body >
        <ResponsiveAppBar />
        {children}

        <footer
          className="bg-black text-center dark:bg-black lg:text-left">
          <div className="p-4 text-left text-neutral-700 dark:text-neutral-200">
            © 2024 Copyright:
            <a
              className="text-neutral-800 dark:text-neutral-400"
              href="https://tw-elements.com/"
            > Gourmet Gurus</a>
          </div>
        </footer>

      </body>
    </html>
  );
}
